if(NOT DEFINED FEED_ENGINE OR NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "FEED_ENGINE and TEST_DIR are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
set(capture "${TEST_DIR}/sample.efc")
execute_process(COMMAND "${FEED_ENGINE}" --help RESULT_VARIABLE help_result OUTPUT_VARIABLE help_output)
if(NOT help_result EQUAL 0 OR NOT help_output MATCHES "--step")
  message(FATAL_ERROR "CLI help failed")
endif()
execute_process(COMMAND "${FEED_ENGINE}" make-sample-capture "${capture}" RESULT_VARIABLE make_result)
if(NOT make_result EQUAL 0)
  message(FATAL_ERROR "sample capture command failed")
endif()
execute_process(COMMAND "${FEED_ENGINE}" replay "${capture}" --speed max RESULT_VARIABLE max_result OUTPUT_VARIABLE max_output)
execute_process(COMMAND "${FEED_ENGINE}" replay "${capture}" --speed 1000000 RESULT_VARIABLE scaled_result OUTPUT_VARIABLE scaled_output)
execute_process(COMMAND "${FEED_ENGINE}" replay "${capture}" --realtime RESULT_VARIABLE realtime_result OUTPUT_VARIABLE realtime_output)
if(NOT max_result EQUAL 0 OR NOT scaled_result EQUAL 0 OR NOT realtime_result EQUAL 0)
  message(FATAL_ERROR "a replay CLI mode failed")
endif()
string(REGEX MATCH "state_hash=0x([0-9a-f]+)" unused "${max_output}")
set(expected_hash "${CMAKE_MATCH_1}")
foreach(output IN ITEMS "${scaled_output}" "${realtime_output}")
  if(NOT output MATCHES "state_hash=0x${expected_hash}")
    message(FATAL_ERROR "replay hash changed: ${output}")
  endif()
endforeach()
file(WRITE "${TEST_DIR}/steps.txt" "\n\n\n")
execute_process(COMMAND "${FEED_ENGINE}" replay "${capture}" --step INPUT_FILE "${TEST_DIR}/steps.txt" RESULT_VARIABLE step_result OUTPUT_VARIABLE step_output)
if(NOT step_result EQUAL 0 OR NOT step_output MATCHES "state_hash=0x${expected_hash}")
  message(FATAL_ERROR "step replay CLI failed")
endif()
