if(NOT DEFINED PROTOCOLC OR NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "PROTOCOLC and TEST_DIR are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
set(valid "protocol Test;\nmessage Ping \"P\" { value: u32_be; name: ascii[4]; }\n")
file(WRITE "${TEST_DIR}/valid.efe" "${valid}")
execute_process(COMMAND "${PROTOCOLC}" "${TEST_DIR}/valid.efe" "${TEST_DIR}/one.hpp" RESULT_VARIABLE first)
execute_process(COMMAND "${PROTOCOLC}" "${TEST_DIR}/valid.efe" "${TEST_DIR}/two.hpp" RESULT_VARIABLE second)
if(NOT first EQUAL 0 OR NOT second EQUAL 0)
  message(FATAL_ERROR "valid schema was rejected")
endif()
file(SHA256 "${TEST_DIR}/one.hpp" one_hash)
file(SHA256 "${TEST_DIR}/two.hpp" two_hash)
if(NOT one_hash STREQUAL two_hash)
  message(FATAL_ERROR "protocol generation is not deterministic")
endif()
file(WRITE "${TEST_DIR}/duplicate_type.efe" "protocol T;\nmessage A \"A\" { x: u8; }\nmessage B \"A\" { y: u8; }\n")
file(WRITE "${TEST_DIR}/duplicate_field.efe" "protocol T;\nmessage A \"A\" { x: u8; x: u8; }\n")
file(WRITE "${TEST_DIR}/unsupported.efe" "protocol T;\nmessage A \"A\" { x: nope; }\n")
file(WRITE "${TEST_DIR}/malformed.efe" "protocol T;\nmessage A \"A\" { x u8; }\n")
file(WRITE "${TEST_DIR}/bad_ascii.efe" "protocol T;\nmessage A \"A\" { x: ascii[0]; }\n")
file(WRITE "${TEST_DIR}/duplicate_name.efe" "protocol T;\nmessage A \"A\" { x: u8; }\nmessage A \"B\" { y: u8; }\n")
file(WRITE "${TEST_DIR}/bad_id.efe" "protocol T;\nmessage A \"AB\" { x: u8; }\n")
foreach(name IN ITEMS duplicate_type duplicate_field unsupported malformed bad_ascii duplicate_name bad_id)
  execute_process(COMMAND "${PROTOCOLC}" "${TEST_DIR}/${name}.efe" "${TEST_DIR}/${name}.hpp" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
  if(result EQUAL 0)
    message(FATAL_ERROR "invalid schema ${name} was accepted")
  endif()
endforeach()
